[package]
name = "meginfo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
csv = "1.2.2"
nom = "7.1.3"
petgraph = "0.6.3"
serde = { version = "1.0", features = ["derive"] }
termtree = "0.4.1"
