// home for giant enums which will clutter the rest of the codebase

use std::default;

// tag code, see fiff/tags.tsv
// is currently missing the MNE-specific tags.
// carries a catchall Code(i32) variant to hold any codes not recognised here
#[derive(Debug, PartialEq, Default)]
pub enum TagKind {
    #[default]
    FileId,
    DirPointer,
    Dir,
    BlockId,
    BlockStart,
    BlockEnd,
    FreeList,
    FreeBlock,
    Nop,
    ParentFileId,
    ParentBlockId,
    BlockName,
    BlockVersion,
    Creator,
    Modifier,
    RefRole,
    RefFileId,
    RefFileNum,
    RefFileName,
    RefBlockId,
    DacqPars,
    DacqStim,
    DeviceType,
    DeviceModel,
    DeviceSerial,
    DeviceSite,
    HeLevelRaw,
    HeliumLevel,
    OrigFileGuid,
    UtcOffset,
    Nchan,
    Sfreq,
    DataPack,
    ChInfo,
    MeasDate,
    Subject,
    Description,
    Nave,
    FirstSample,
    LastSample,
    AspectKind,
    RefEvent,
    Experimenter,
    DigPoint,
    ChPosVec,
    HpiSlopes,
    HpiNcoil,
    ReqEvent,
    ReqLimit,
    Lowpass,
    BadChs,
    ArtefRemoval,
    CoordTrans,
    Highpass,
    ChCalsVec,
    HpiBadChs,
    HpiCorrCoeff,
    EventComment,
    NoSamples,
    FirstTime,
    SubaveSize,
    SubaveFirst,
    Name,
    DigString,
    LineFreq,
    HpiCoilFreq,
    SignalChannel,
    HpiCoilMoments,
    HpiFitGoodness,
    HpiFitAccept,
    HpiFitGoodLimit,
    HpiFitDistLimit,
    HpiCoilNo,
    HpiCoilsUsed,
    HpiDigitizationOrder,
    ChScanNo,
    ChLogicalNo,
    ChKind,
    ChRange,
    ChCal,
    ChPos,
    ChUnit,
    ChUnitMul,
    ChDacqName,
    SssFrame,
    SssJob,
    SssOrigin,
    SssOrdIn,
    SssOrdOut,
    SssNmag,
    SssComponents,
    SssCalChans,
    SssCalCorrs,
    SssStCorr,
    SssBaseIn,
    SssBaseOut,
    SssBaseVirt,
    SssNorm,
    SssIterate,
    SssNfree,
    SssStLength,
    GantryType,
    GantryModel,
    GantryAngle,
    SssOperator,
    SssPsinv,
    SssCtc,
    DataBuffer,
    DataSkip,
    Epoch,
    DataSkipSamp,
    TimeStamp,
    ChCoilType,
    ChCoordFrame,
    SubjId,
    SubjFirstName,
    SubjMiddleName,
    SubjLastName,
    SubjBirthDay,
    SubjSex,
    SubjHand,
    SubjWeight,
    SubjHeight,
    SubjComment,
    SubjHisId,
    ProjId,
    ProjName,
    ProjAim,
    ProjPersons,
    ProjComment,
    EventChannels,
    EventList,
    EventChannel,
    EventBits,
    SquidBias,
    SquidOffset,
    SquidGate,
    DecouplerMatrix,
    CtmOpenAmps,
    CtmOpenPhase,
    CtmClosAmps,
    CtmClosPhase,
    CtmClosDote,
    CtmOpenDote,
    CtmExciFreq,
    RefPath,
    VolumeType,
    MriSourceFormat,
    MriPixelEncoding,
    MriPixelDataOffset,
    MriPixelScale,
    MriPixelData,
    MriPixelOverlayEncoding,
    MriPixelOverlayData,
    MriBoundingBox,
    MriWidth,
    MriWidthM,
    MriHeight,
    MriHeightM,
    MriDepth,
    MriDepthM,
    MriThickness,
    MriSceneAim,
    MriCalibrationScale,
    MriCalibrationOffset,
    MriOrigSourcePath,
    MriOrigSourceFormat,
    MriOrigPixelEncoding,
    MriOrigPixelDataOffset,
    MriTime,
    MriVoxelData,
    MriVoxelEncoding,
    VoxelNchannels,
    MriDiffusionWeight,
    MriDiffusionParam,
    MriMrilabSetup,
    MriSegRegionId,
    ConductorModelKind,
    SphereOrigin,
    SphereCoordFrame,
    SphereLayers,
    BemSurfId,
    BemSurfName,
    BemSurfNnode,
    BemSurfNtri,
    BemSurfNodes,
    BemSurfTriangles,
    BemSurfNormals,
    BemSurfCurvs,
    BemSurfCurvValues,
    BemPotSolution,
    BemApprox,
    BemCoordFrame,
    BemSigma,
    SourceDipole,
    BeamformerInstructions,
    XfitLeadProducts,
    XfitMapProducts,
    XfitGradMapProducts,
    XfitVolIntegration,
    XfitIntegrationRadius,
    XfitConductorModelName,
    XfitConductorModelTransName,
    XfitContSurfType,
    ProjItemKind,
    ProjItemTime,
    ProjItemIgnChs,
    ProjItemNvec,
    ProjItemVectors,
    ProjItemDefinition,
    ProjItemChNameList,
    XplotterLayout,
    VolId,
    VolName,
    VolOwnerId,
    VolOwnerName,
    VolOwnerRealName,
    VolType,
    VolHost,
    VolRealRoot,
    VolSymbolicRoot,
    VolMountPoint,
    VolBlocks,
    VolFreeBlocks,
    VolAvailBlocks,
    VolBlockSize,
    VolDirectory,
    MemDataBuffer,
    Code(i32),
}

impl TagKind {
    pub fn from_code(code: i32) -> Self {
        match code {
            100 => TagKind::FileId,
            101 => TagKind::DirPointer,
            102 => TagKind::Dir,
            103 => TagKind::BlockId,
            104 => TagKind::BlockStart,
            105 => TagKind::BlockEnd,
            106 => TagKind::FreeList,
            107 => TagKind::FreeBlock,
            108 => TagKind::Nop,
            109 => TagKind::ParentFileId,
            110 => TagKind::ParentBlockId,
            111 => TagKind::BlockName,
            112 => TagKind::BlockVersion,
            113 => TagKind::Creator,
            114 => TagKind::Modifier,
            115 => TagKind::RefRole,
            116 => TagKind::RefFileId,
            117 => TagKind::RefFileNum,
            118 => TagKind::RefFileName,
            120 => TagKind::RefBlockId,
            150 => TagKind::DacqPars,
            151 => TagKind::DacqStim,
            152 => TagKind::DeviceType,
            153 => TagKind::DeviceModel,
            154 => TagKind::DeviceSerial,
            155 => TagKind::DeviceSite,
            156 => TagKind::HeLevelRaw,
            157 => TagKind::HeliumLevel,
            158 => TagKind::OrigFileGuid,
            159 => TagKind::UtcOffset,
            200 => TagKind::Nchan,
            201 => TagKind::Sfreq,
            202 => TagKind::DataPack,
            203 => TagKind::ChInfo,
            204 => TagKind::MeasDate,
            205 => TagKind::Subject,
            206 => TagKind::Description,
            207 => TagKind::Nave,
            208 => TagKind::FirstSample,
            209 => TagKind::LastSample,
            210 => TagKind::AspectKind,
            211 => TagKind::RefEvent,
            212 => TagKind::Experimenter,
            213 => TagKind::DigPoint,
            214 => TagKind::ChPosVec,
            215 => TagKind::HpiSlopes,
            216 => TagKind::HpiNcoil,
            217 => TagKind::ReqEvent,
            218 => TagKind::ReqLimit,
            219 => TagKind::Lowpass,
            220 => TagKind::BadChs,
            221 => TagKind::ArtefRemoval,
            222 => TagKind::CoordTrans,
            223 => TagKind::Highpass,
            224 => TagKind::ChCalsVec,
            225 => TagKind::HpiBadChs,
            226 => TagKind::HpiCorrCoeff,
            227 => TagKind::EventComment,
            228 => TagKind::NoSamples,
            229 => TagKind::FirstTime,
            230 => TagKind::SubaveSize,
            231 => TagKind::SubaveFirst,
            233 => TagKind::Name,
            234 => TagKind::DigString,
            235 => TagKind::LineFreq,
            236 => TagKind::HpiCoilFreq,
            237 => TagKind::SignalChannel,
            240 => TagKind::HpiCoilMoments,
            241 => TagKind::HpiFitGoodness,
            242 => TagKind::HpiFitAccept,
            243 => TagKind::HpiFitGoodLimit,
            244 => TagKind::HpiFitDistLimit,
            245 => TagKind::HpiCoilNo,
            246 => TagKind::HpiCoilsUsed,
            247 => TagKind::HpiDigitizationOrder,
            250 => TagKind::ChScanNo,
            251 => TagKind::ChLogicalNo,
            252 => TagKind::ChKind,
            253 => TagKind::ChRange,
            254 => TagKind::ChCal,
            255 => TagKind::ChPos,
            256 => TagKind::ChUnit,
            257 => TagKind::ChUnitMul,
            258 => TagKind::ChDacqName,
            263 => TagKind::SssFrame,
            264 => TagKind::SssJob,
            265 => TagKind::SssOrigin,
            266 => TagKind::SssOrdIn,
            267 => TagKind::SssOrdOut,
            268 => TagKind::SssNmag,
            269 => TagKind::SssComponents,
            270 => TagKind::SssCalChans,
            271 => TagKind::SssCalCorrs,
            272 => TagKind::SssStCorr,
            273 => TagKind::SssBaseIn,
            274 => TagKind::SssBaseOut,
            275 => TagKind::SssBaseVirt,
            276 => TagKind::SssNorm,
            277 => TagKind::SssIterate,
            278 => TagKind::SssNfree,
            279 => TagKind::SssStLength,
            280 => TagKind::GantryType,
            281 => TagKind::GantryModel,
            282 => TagKind::GantryAngle,
            290 => TagKind::SssOperator,
            291 => TagKind::SssPsinv,
            292 => TagKind::SssCtc,
            300 => TagKind::DataBuffer,
            301 => TagKind::DataSkip,
            302 => TagKind::Epoch,
            303 => TagKind::DataSkipSamp,
            305 => TagKind::TimeStamp,
            350 => TagKind::ChCoilType,
            351 => TagKind::ChCoordFrame,
            400 => TagKind::SubjId,
            401 => TagKind::SubjFirstName,
            402 => TagKind::SubjMiddleName,
            403 => TagKind::SubjLastName,
            404 => TagKind::SubjBirthDay,
            405 => TagKind::SubjSex,
            406 => TagKind::SubjHand,
            407 => TagKind::SubjWeight,
            408 => TagKind::SubjHeight,
            409 => TagKind::SubjComment,
            410 => TagKind::SubjHisId,
            500 => TagKind::ProjId,
            501 => TagKind::ProjName,
            502 => TagKind::ProjAim,
            503 => TagKind::ProjPersons,
            504 => TagKind::ProjComment,
            600 => TagKind::EventChannels,
            601 => TagKind::EventList,
            602 => TagKind::EventChannel,
            603 => TagKind::EventBits,
            701 => TagKind::SquidBias,
            702 => TagKind::SquidOffset,
            703 => TagKind::SquidGate,
            800 => TagKind::DecouplerMatrix,
            801 => TagKind::CtmOpenAmps,
            802 => TagKind::CtmOpenPhase,
            803 => TagKind::CtmClosAmps,
            804 => TagKind::CtmClosPhase,
            805 => TagKind::CtmClosDote,
            806 => TagKind::CtmOpenDote,
            807 => TagKind::CtmExciFreq,
            1101 => TagKind::RefPath,
            2001 => TagKind::VolumeType,
            2002 => TagKind::MriSourceFormat,
            2003 => TagKind::MriPixelEncoding,
            2004 => TagKind::MriPixelDataOffset,
            2005 => TagKind::MriPixelScale,
            2006 => TagKind::MriPixelData,
            2007 => TagKind::MriPixelOverlayEncoding,
            2008 => TagKind::MriPixelOverlayData,
            2009 => TagKind::MriBoundingBox,
            2010 => TagKind::MriWidth,
            2011 => TagKind::MriWidthM,
            2012 => TagKind::MriHeight,
            2013 => TagKind::MriHeightM,
            2014 => TagKind::MriDepth,
            2015 => TagKind::MriDepthM,
            2016 => TagKind::MriThickness,
            2017 => TagKind::MriSceneAim,
            2018 => TagKind::MriCalibrationScale,
            2019 => TagKind::MriCalibrationOffset,
            2020 => TagKind::MriOrigSourcePath,
            2021 => TagKind::MriOrigSourceFormat,
            2022 => TagKind::MriOrigPixelEncoding,
            2023 => TagKind::MriOrigPixelDataOffset,
            2024 => TagKind::MriTime,
            2030 => TagKind::MriVoxelData,
            2031 => TagKind::MriVoxelEncoding,
            2032 => TagKind::VoxelNchannels,
            2040 => TagKind::MriDiffusionWeight,
            2041 => TagKind::MriDiffusionParam,
            2100 => TagKind::MriMrilabSetup,
            2200 => TagKind::MriSegRegionId,
            3000 => TagKind::ConductorModelKind,
            3001 => TagKind::SphereOrigin,
            3002 => TagKind::SphereCoordFrame,
            3003 => TagKind::SphereLayers,
            3101 => TagKind::BemSurfId,
            3102 => TagKind::BemSurfName,
            3103 => TagKind::BemSurfNnode,
            3104 => TagKind::BemSurfNtri,
            3105 => TagKind::BemSurfNodes,
            3106 => TagKind::BemSurfTriangles,
            3107 => TagKind::BemSurfNormals,
            3108 => TagKind::BemSurfCurvs,
            3109 => TagKind::BemSurfCurvValues,
            3110 => TagKind::BemPotSolution,
            3111 => TagKind::BemApprox,
            3112 => TagKind::BemCoordFrame,
            3113 => TagKind::BemSigma,
            3201 => TagKind::SourceDipole,
            3300 => TagKind::BeamformerInstructions,
            3401 => TagKind::XfitLeadProducts,
            3402 => TagKind::XfitMapProducts,
            3403 => TagKind::XfitGradMapProducts,
            3404 => TagKind::XfitVolIntegration,
            3405 => TagKind::XfitIntegrationRadius,
            3406 => TagKind::XfitConductorModelName,
            3407 => TagKind::XfitConductorModelTransName,
            3408 => TagKind::XfitContSurfType,
            3411 => TagKind::ProjItemKind,
            3412 => TagKind::ProjItemTime,
            3413 => TagKind::ProjItemIgnChs,
            3414 => TagKind::ProjItemNvec,
            3415 => TagKind::ProjItemVectors,
            3416 => TagKind::ProjItemDefinition,
            3417 => TagKind::ProjItemChNameList,
            3501 => TagKind::XplotterLayout,
            4001 => TagKind::VolId,
            4002 => TagKind::VolName,
            4003 => TagKind::VolOwnerId,
            4004 => TagKind::VolOwnerName,
            4005 => TagKind::VolOwnerRealName,
            4006 => TagKind::VolType,
            4007 => TagKind::VolHost,
            4008 => TagKind::VolRealRoot,
            4009 => TagKind::VolSymbolicRoot,
            4010 => TagKind::VolMountPoint,
            4011 => TagKind::VolBlocks,
            4012 => TagKind::VolFreeBlocks,
            4013 => TagKind::VolAvailBlocks,
            4014 => TagKind::VolBlockSize,
            4015 => TagKind::VolDirectory,
            10300 => TagKind::MemDataBuffer,
            _ => TagKind::Code(code),
        }
    }
}

#[derive(Debug, PartialEq, Default)]
pub enum BlockKind {
    #[default]
    Root,
    Meas,
    MeasInfo,
    RawData,
    ProcessedData,
    Evoked,
    Aspect,
    Subject,
    Isotrak,
    HpiMeas,
    HpiResult,
    HpiCoil,
    Project,
    ContinuousData,
    ChInfo,
    Void,
    Events,
    Index,
    DacqPars,
    Ref,
    IasRawData,
    IasAspect,
    HpiSubsystem,
    PhantomSubsystem,
    StatusSubsystem,
    DeviceInfo,
    HeliumInfo,
    ChannelInfo,
    StructuralData,
    VolumeData,
    VolumeSlice,
    Scenery,
    Scene,
    MriSeg,
    MriSegRegion,
    Sphere,
    Bem,
    BemSurf,
    ConductorModel,
    Ssp,
    SspItem,
    XfitAux,
    FiffCov,
    BadChannels,
    VolInfo,
    DataCorrection,
    ChannelsDecoupler,
    SssInfo,
    SssCalAdjust,
    SssStInfo,
    SssBases,
    SssOperator,
    CtMeas,
    SssExpansion,
    Ias,
    ProcessingHistory,
    ProcessingRecord,
    Code(i32),
}

impl BlockKind {
    pub fn from_code(code: i32) -> Self {
        match code {
            999 => BlockKind::Root,
            100 => BlockKind::Meas,
            101 => BlockKind::MeasInfo,
            102 => BlockKind::RawData,
            103 => BlockKind::ProcessedData,
            104 => BlockKind::Evoked,
            105 => BlockKind::Aspect,
            106 => BlockKind::Subject,
            107 => BlockKind::Isotrak,
            108 => BlockKind::HpiMeas,
            109 => BlockKind::HpiResult,
            110 => BlockKind::HpiCoil,
            111 => BlockKind::Project,
            112 => BlockKind::ContinuousData,
            113 => BlockKind::ChInfo,
            114 => BlockKind::Void,
            115 => BlockKind::Events,
            116 => BlockKind::Index,
            117 => BlockKind::DacqPars,
            118 => BlockKind::Ref,
            119 => BlockKind::IasRawData,
            120 => BlockKind::IasAspect,
            121 => BlockKind::HpiSubsystem,
            122 => BlockKind::PhantomSubsystem,
            123 => BlockKind::StatusSubsystem,
            124 => BlockKind::DeviceInfo,
            125 => BlockKind::HeliumInfo,
            126 => BlockKind::ChannelInfo,
            200 => BlockKind::StructuralData,
            201 => BlockKind::VolumeData,
            202 => BlockKind::VolumeSlice,
            203 => BlockKind::Scenery,
            204 => BlockKind::Scene,
            205 => BlockKind::MriSeg,
            206 => BlockKind::MriSegRegion,
            300 => BlockKind::Sphere,
            310 => BlockKind::Bem,
            311 => BlockKind::BemSurf,
            312 => BlockKind::ConductorModel,
            313 => BlockKind::Ssp,
            314 => BlockKind::SspItem,
            315 => BlockKind::XfitAux,
            355 => BlockKind::FiffCov,
            359 => BlockKind::BadChannels,
            400 => BlockKind::VolInfo,
            500 => BlockKind::DataCorrection,
            501 => BlockKind::ChannelsDecoupler,
            502 => BlockKind::SssInfo,
            503 => BlockKind::SssCalAdjust,
            504 => BlockKind::SssStInfo,
            505 => BlockKind::SssBases,
            506 => BlockKind::SssOperator,
            507 => BlockKind::CtMeas,
            508 => BlockKind::SssExpansion,
            510 => BlockKind::Ias,
            900 => BlockKind::ProcessingHistory,
            901 => BlockKind::ProcessingRecord,
            _ => BlockKind::Code(code),
        }
    }
}
